sudo: required
language: generic
services:
  - docker

branches:
  except:
   - gh-pages

env:
  global:
    - CONTAINER_NAME=catkin_pip_docker
  # This will check any ROS distro supported on this OS
  # checking devel and install separately so that they don't influence each other (dependencies, path, env, etc.)
  matrix:
    - CI_ROS_DISTRO=indigo ROS_FLOW=devel
    - CI_ROS_DISTRO=indigo ROS_FLOW=install
    - CI_ROS_DISTRO=jade ROS_FLOW=devel
    - CI_ROS_DISTRO=jade ROS_FLOW=install
    - CI_ROS_DISTRO=kinetic ROS_FLOW=devel
    - CI_ROS_DISTRO=kinetic ROS_FLOW=install
  # TODO : test all possible flows (installing deps on devel or not, etc.)

install:
  - docker pull ros/${CI_ROS_DISTRO}-ros-core
  - docker run --name ${CONTAINER_NAME} -d -t ros/${CI_ROS_DISTRO}-ros-core -v $HOME:$HOME /bin/bash > container.id
  - docker ps -a
  - docker exec -t ${TAG} hostname
  - docker exec -t ${TAG} uname -a
  - docker exec -t ${TAG} cat /etc/lsb-release

# full ROS setup, build and test
script:
  - CONTAINER_ID=$(cat container.id)
  - docker ps -a
  - docker exec -t ${TAG} rospack profile
  - docker exec -t ${TAG} ./travis_checks.sh
  - docker stop "${CONTAINER_ID}"

notifications:
  email: false

